In [64]:
import tensorflow as tf
import tensorflow.keras
import os
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import pandas as pd
from tensorflow.keras import models
from tensorflow.keras import layers
from sklearn.metrics import confusion_matrix,classification_report
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing import image
from tensorflow.keras.utils import to_categorical
import numpy as np


In [2]:
train_dir='D:/Data_Science/DS_Project/Apreal/train/'
test_dir='D:/Data_Science/DS_Project/Apreal/test/'

In [3]:
train_image=ImageDataGenerator(1/255)

In [4]:
len(os.listdir(train_dir))

60000

In [5]:
len(os.listdir(test_dir))

10000

In [7]:
xtrain=[]
for i in range(40000):
    i=i+1
    dir=train_dir+str(i)+'.png'
    img=image.load_img(dir)
    img=img_to_array(img)/255
    img=img[:,:,0]
    xtrain.append(img)

In [9]:
xtest=[]
for i in range(20000):
    i=i+40001
    dir=train_dir+str(i)+'.png'
    img=image.load_img(dir)
    img=img_to_array(img)/255
    img=img[:,:,0]
    xtest.append(img)

In [16]:
df=np.array(xtrain)

In [24]:
df.shape

(60000, 28, 28)

In [25]:
data=df.reshape(60000,28*28)

In [27]:
train=data[0:40000,:]
test=data[40000:60000,:]

In [38]:
train.shape

(40000, 784)

id  label
0          1      9
1          2      0
2          3      0
3          4      3
4          5      0
...      ...    ...
39995  39996      7
39996  39997      4
39997  39998      0
39998  39999      0
39999  40000      0

[40000 rows x 2 columns]

In [21]:
train.to_csv('D:\Data_Science\DS_Project\Apreal\Appreal.csv')

In [44]:
y_label=pd.read_csv(r'D:\Data_Science\DS_Project\Apreal\train.csv')

In [45]:
y_train=to_categorical(y_label['label'])

In [46]:
ytrain=y_train[0:40000]
ytest=y_train[40000:60000]

In [50]:
model=models.Sequential()

In [51]:
model.add(layers.Dense(512,activation='relu',input_shape=(28*28,)))

In [52]:
model.add(layers.Dense(10,activation='softmax'))
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [53]:
ytrain.shape

(40000, 10)

In [54]:
train.shape

(40000, 784)

In [75]:
model.fit(train,ytrain,epochs=5,batch_size=120) # this was executed twice hence there was overfitting observed and test score went down

Epoch 1/5
334/334 [==============================] - 3s 8ms/step - loss: 0.2876 - accuracy: 0.8914
Epoch 2/5
334/334 [==============================] - 2s 7ms/step - loss: 0.2735 - accuracy: 0.9001
Epoch 3/5
334/334 [==============================] - 2s 7ms/step - loss: 0.2576 - accuracy: 0.9061
Epoch 4/5
334/334 [==============================] - 2s 7ms/step - loss: 0.2494 - accuracy: 0.9066
Epoch 5/5
334/334 [==============================] - 3s 9ms/step - loss: 0.2369 - accuracy: 0.9122


In [76]:
predict=model.predict(test)

In [77]:
prediction=predict.argmax(axis=1)

In [78]:
len(prediction)

20000

In [79]:
confusion_matrix(prediction,ytest.argmax(axis=1))

array([[1746,    0,   36,   24,    1,    2,  319,    0,    5,    0],
       [  56, 1989,   21,  158,   51,    0,   39,    0,    3,    0],
       [  39,    1, 1315,    3,   38,    0,  147,    0,    1,    0],
       [  60,   12,   20, 1630,   15,    0,   47,    0,    3,    0],
       [  17,    0,  617,  145, 1921,    0,  512,    0,   18,    0],
       [   1,    0,    0,    0,    0, 1928,    0,   29,    5,   24],
       [  82,    1,   36,    9,   11,    0,  839,    0,    1,    0],
       [   0,    0,    0,    0,    0,   38,    0, 1914,    9,  198],
       [  17,    1,   20,    9,    6,    6,   31,    2, 1954,    0],
       [   1,    0,    0,    0,    0,    9,    0,   13,    1, 1794]],
      dtype=int64)

In [80]:
print(classification_report(prediction,ytest.argmax(axis=1)))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84      2133
           1       0.99      0.86      0.92      2317
           2       0.64      0.85      0.73      1544
           3       0.82      0.91      0.87      1787
           4       0.94      0.59      0.73      3230
           5       0.97      0.97      0.97      1987
           6       0.43      0.86      0.58       979
           7       0.98      0.89      0.93      2159
           8       0.98      0.96      0.97      2046
           9       0.89      0.99      0.94      1818

    accuracy                           0.85     20000
   macro avg       0.85      0.87      0.85     20000
weighted avg       0.89      0.85      0.86     20000



In [67]:
from sklearn.linear_model import LogisticRegression

In [68]:
lo=LogisticRegression()

In [70]:
lo.fit(train,ytrain.argmax(axis=1))

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [71]:
lo.predict(test)

array([7, 7, 4, ..., 3, 0, 5], dtype=int64)

In [73]:
confusion_matrix(lo.predict(test),ytest.argmax(axis=1))

array([[1653,    9,   32,   61,    3,    4,  297,    0,   10,    0],
       [   8, 1931,    6,   20,    4,    0,    3,    0,    0,    0],
       [  34,    5, 1559,   15,  176,    1,  231,    1,   12,    0],
       [ 111,   47,   21, 1743,   58,    0,   71,    0,   13,    0],
       [   8,    4,  238,   72, 1620,    0,  176,    0,    5,    0],
       [   2,    1,    2,    0,    0, 1846,    0,   79,   11,   33],
       [ 177,    5,  188,   60,  172,    1, 1123,    0,   37,    0],
       [   1,    1,    0,    1,    0,   83,    0, 1818,   13,   70],
       [  25,    1,   19,    6,   10,   13,   33,    1, 1896,    0],
       [   0,    0,    0,    0,    0,   35,    0,   59,    3, 1913]],
      dtype=int64)

In [74]:
print(classification_report(lo.predict(test),ytest.argmax(axis=1)))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81      2069
           1       0.96      0.98      0.97      1972
           2       0.75      0.77      0.76      2034
           3       0.88      0.84      0.86      2064
           4       0.79      0.76      0.78      2123
           5       0.93      0.94      0.93      1974
           6       0.58      0.64      0.61      1763
           7       0.93      0.91      0.92      1987
           8       0.95      0.95      0.95      2004
           9       0.95      0.95      0.95      2010

    accuracy                           0.86     20000
   macro avg       0.85      0.85      0.85     20000
weighted avg       0.86      0.86      0.86     20000

